### ISSUE TITLE
Passing in className will overwrite default classes

### ISSUE THREAD

**Issue by gsklee** [KyleAMathews/react-spinkit#13]
If I do something like this:

```javascript
<Spinner className="center" spinnerName='double-bounce' />
```

I'll get something like this: `<div class="center">` instead of something like `<div class="spinner double-bounce center">` and the spinner won't work as a result.

**Comment by KyleAMathews** [comment]
Thanks for the bug report!

**Comment by gsklee** [comment]
@KyleAMathews :+1:
