### ISSUE TITLE
Be able to pass color

### ISSUE THREAD

**Issue by lapanoid** [KyleAMathews/react-spinkit#16]
Now it is hardly possible to use in production because color of spinners hardcoded in styles.

**Comment by KyleAMathews** [comment]
You can write your own css to override the default color.

**Comment by lapanoid** [comment]
What the point to make react component then, if even to control color (essential thing)  I have to change css?

**Comment by dorthwein** [comment]
I'd second this - would you accept a pull request on this?

**Comment by KyleAMathews** [comment]
@dorthwein yup!
