### ISSUE TITLE
1.1.4: Cannot find module 'cssify' from 'node_modules/react-spinkit'

### ISSUE THREAD

**Issue by idolize** [KyleAMathews/react-spinkit#21]
I'm using Browseify to build my app, and because `cssify` is only a `devDependency` it does not appear to install.

As a result, trying to build my app always results in the following error:

```
Cannot find module 'cssify' from 'node_modules/react-spinkit'
```

**Comment by KyleAMathews** [comment]
Cssify is in devdependencies for the demo. You're expected to install and configure cssify yourself for your application.

**Comment by idolize** [comment]
Hmm, okay, well in that case it would probably be good to make that a bit more obvious in the docs or something. Getting a missing dependency error when building does not make it obvious that this is the expected behavior.
