### ISSUE TITLE
Error after launch my app

### ISSUE THREAD

**Issue by Xurma2** [KyleAMathews/react-spinkit#23]
Cannot find module '....cssify' from 'node_modules\react-spinkit\css' Error: Cannot
find module '....cssify' from 'node_modules\react-spinkit\css'
    at node_modules\resolve\lib\async.js:46:17
    at process (node_modules\resolve\lib\async.js:173:43)
    at ondir (node_modules\resolve\lib\async.js:188:17)
    at load (node_modules\resolve\lib\async.js:69:43)
    at onex (node_modules\resolve\lib\async.js:92:31)
    at node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)

react-spinkit - ^1.1.4
cssify            - ^1.0.0
npm              - 3.3.12
nodejs          - v5.1.0

**Comment by KyleAMathews** [comment]
Looks like cssify isn't installed or configured correctly.

**Comment by Xurma2** [comment]
Спасибо за неоценимую помощь, в решении мой проблемы. Вы открыли мне глаза mr. Kyle

**Comment by ses4j** [comment]
@Xurma2 I believe your problem is with a Windows-related bug in cssify, such as reported by https://github.com/davidguttman/cssify/issues/46
