### ISSUE TITLE
Full compatibility with React 15

### ISSUE THREAD

**Issue by guidupuy** [KyleAMathews/react-spinkit#30]
`react-spinkit` uses the `cjsx-loader` webpack loader, which in turn also uses the `coffee-react-transform` webpack loader at version `^3.2.0`.

I've added a pull request over at the `cjsx-loader` repo so you can update the dependency there if that's ok with you. If so, when that's done can you update the dependencies here as well?

Thanks a million, and thank you for `react-spinkit`!

**Comment by KyleAMathews** [comment]
The new cjsx-loader is out but it isn't actually a dependency of this module so there's nothing that needs updated here.

**Comment by KyleAMathews** [comment]
Ooops, I did need to make a new release with the new version of coffee-react-transform so just did that :-)

**Comment by guidupuy** [comment]
Great, thanks!
