### ISSUE TITLE
React-Spinkit component has to be lower cased

### ISSUE THREAD

**Issue by benbieler** [KyleAMathews/react-spinkit#31]
If the loading spinner [here] (https://github.com/Sententiaregum/Sententiaregum/blob/master/src/Frontend/components/app/markup/LoadableButtonBar.js#L14) is upper cased the mocha-babel testsuite will throw an exception (spinner instead of Spinner will work). Do you know what could be the reason for this?

**Comment by benbieler** [comment]
ping?

**Comment by KyleAMathews** [comment]
No idea why the case would matter. Components have to be upper-cased in JSX for the JSX transpilation to work. Highly unlikely though this has anything to do with react-spinkit as I and plenty of others have used it the normal way without trouble. If you do isolate it to something goofy here, please report back! Preferably with a PR fixing it ;-)
