### ISSUE TITLE
Coloring the spinners

### ISSUE THREAD

**Issue by canibanoglu** [KyleAMathews/react-spinkit#37]
Hello,

I've seen that this has been proposed before and you said there that you would accept a pull request implementing this. I just wanted to make sure that you are still open to the idea before I actually implement this.

Kind regards,

Can

**Comment by canibanoglu** [comment]
Actually not only coloring but I think passing down styles would be hugely beneficial. Currently the only way to style the spinner is through CSS and that actually binds my CSS declarations to the HTML generated which is far from ideal under React, imo.

**Comment by canibanoglu** [comment]
Morever, I think there should be support for adding multiple class to the container div. Currently there is a way around that by separating multiple class names in the overrideSpinnerClassName prop, but that is a bit clumsy I think.

**Comment by ml9951** [comment]
Any progress on this?

**Comment by KyleAMathews** [comment]
Open to a PR.

**Comment by merrywhether** [comment]
Fixed in 3.0
