### ISSUE TITLE
Add support for universal rendering

### ISSUE THREAD

**Issue by aight8** [KyleAMathews/react-spinkit#40]
Because the server should not really rendered on server side (it's only temporary for the client normally) maybe just render "null" is quick solution.

**Comment by KyleAMathews** [comment]
Is there something broken right now? If not, it seems more bother than it's worth to try to not render on the server as a slight optimization.

**Comment by aight8** [comment]
```
/APP_PATH/node_modules/react-spinkit/css/fade-in.css:1
(function (exports, require, module, __filename, __dirname) { @-webkit-keyframes fade-in {
                                                              ^
SyntaxError: Unexpected token ILLEGAL
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (/APP_PATH/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/APP_PATH/node_modules/react-spinkit/dist/index.js:19:1)
```

**Comment by sebfek** [comment]
I dont get this exception really. The css and style loader is the only loaders. It seems to be the @ character is a special token somehow (like @import).

**Comment by KyleAMathews** [comment]
No it's for animations https://developer.mozilla.org/en-US/docs/Web/CSS/@keyframes

If you're seeing this error then it's because you don't have your webpack config setup correctly.

**Comment by KyleAMathews** [comment]
Similar to this issue https://github.com/KyleAMathews/react-spinkit/issues/41

**Comment by sebfek** [comment]
Maybe an advice to users would be nice. I find a solution fow this and post it here.

**Comment by lynndylanhurley** [comment]
@KyleAMathews - can you post the webpack config that you're using?

**Comment by 1312624** [comment]
I have a same problem, this is my webpack.config.js

```
           {
                test: /\.css$/,
                use: [
                    {
                        loader : 'style-loader'
                    },
                    {
                        loader : 'css-loader',
                        options : {
                            modules : true
                        }
                    }
                ]
            }
```

Is that true? how can I fix this problem
