### ISSUE TITLE
Dimensions off by default?

### ISSUE THREAD

**Issue by philip-peterson** [KyleAMathews/react-spinkit#48]
Hi there,

I noticed that at least for wandering-cubes, width and height are about 1/2 the actual value they should be to represent their actual dimensions on screen. (They are 27x27, should probably be about 54x54). This was just a problem for me because I was trying to center-position the animation as a flex item. Thought it might be worth mentioning.

Thanks!

**Comment by KyleAMathews** [comment]
Oh! Hadn't noticed, would love a pr to fix it!

**Comment by merrywhether** [comment]
@philip-peterson This is fixed in the 3.0 release
