### ISSUE TITLE
Browserify complains about CSS

### ISSUE THREAD

**Issue by 0x80** [KyleAMathews/react-spinkit#9]
I'm getting this from my Grunt Browserify output.  Are these files really CSS or do they need some sort of preprocessing?

```
>> /Users/me/project/node_modules/react-spinkit/css/fade-in.css:1
>> @-webkit-keyframes fade-in {
>> ^
>> ParseError: Unexpected character '@'
```

**Comment by KyleAMathews** [comment]
You need to add a CSS transformer like [CSSify](https://github.com/davidguttman/cssify). Also the code is confusing atm because I didn't realize this when I first wrote this that you can't conditionally require things so CSS is always required.

**Comment by 0x80** [comment]
Why don't you leave it up to the user to import the css into their own? Like with material-ui for example you place something like this in your less or sass files:

@import "node_modules/material-ui/src/less/scaffolding.less";
@import "node_modules/material-ui/src/less/components.less";

Then you can let people manage their own without forcing them into a certain workflow, and you don't have to worry about it.

**Comment by blakeembrey** [comment]
@KyleAMathews You can't use CSSify in modules from your application. You need to add it as a dependency and set it in your `package.json` like https://github.com/substack/node-browserify#browserifytransform

**Comment by KyleAMathews** [comment]
@blakeembrey you can't do something like `browserify -t cssify entry.js > bundle.js`?

Also free-style looks pretty cool! Only problem here is animation doesn't work for inline styles and I want server rendered code to work before the JS code is loaded.

**Comment by blakeembrey** [comment]
@KyleAMathews Not with my own application with this as a dependency, since transforms are only for your own module (not dependencies). If you want `CSSify` to work with this, you need to put it in the `package.json` file as described under the `browserify` property.

The inline styles is a good point (I actually opted for SVG over this module, since this was causing me too much grief to bother fixing), but I'm not sure I follow what you mean with the server rendered code? It'd be the same sort of output as this?

**Comment by KyleAMathews** [comment]
@blakeembrey huh... hadn't realized that as I use Webpack and its "loaders" override all requires regardless of where in the code so this module just works for me.

By server rendered code — perhaps I was misunderstanding how your module works. I was assuming it works by injecting generated css in a style tag in the header using JS after the web page boots... I think I've seen some other projects that do this. But looking at it again, there's a way to add the CSS to the head on the server using `getStyles()`? Is there also a way to pull out the css into webpack similar to https://github.com/js-next/react-style-webpack-plugin ?

**Comment by blakeembrey** [comment]
@KyleAMathews Interesting - that actually sounds challenging since `free-style` supports multiple style sheets and instances. The goal is to generate stylesheets themselves from JavaScript (to support the animations)?

**Comment by KyleAMathews** [comment]
@blakeembrey yeah exactly. Generate the css from JS and have some way for Webpack/Browserify/etc to pull them out into an external css file similar to the react-style plugin.

**Comment by blakeembrey** [comment]
Yes, it should be possible for something like what they're doing.

**Comment by ansiv** [comment]
And what about the solution? I have the same issue.

**Comment by KyleAMathews** [comment]
@ansiv @blakeembrey I think the simplest thing to do atm it sounds like is to add the browersify specific css transform instructions to the package.json. And then hope that the React community decides soon on a React native way of handling css rules that don't work with inline styles.

**Comment by KyleAMathews** [comment]
@ansiv @blakeembrey could one of you create a PR?
